# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-20.04

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    cd $HOME
    wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.35.0/pmd-bin-6.35.0.zip
    unzip pmd-bin-6.35.0.zip
    alias pmd="$HOME/pmd-bin-6.35.0/bin/run.sh pmd"
    pmd -d /usr/src -R rulesets/java/quickstart.xml -f text
  displayName: 'Run a multi-line script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'