name: Superlinter checks
on: [push, pull_request]

jobs:
  build:
    name: Superlint Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Lint code using superlinter
        uses: github/super-linter@v4.0.2
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

